title: "Duncan Browne"
theme: "eon"
baseURL: "https://DBBrowne.github.io/blog"
#baseURL: 'http://localhost:8801'
# for multiple authors, see
# https://discourse.gohugo.io/t/site-author-usage/31459/8?u=coolaj86
Author:
  name: "Duncan Browne"
  email: "gh@dbb.tools"
copyright: "© Duncan Browne"
languageCode: "en-us"

Params:
  gravatar: true
  show_edit: "Suggest Edit"
  git_repo: "https://github.com/DBBrowne/blog"
  git_branch: "main"
  git_host: "github"
  utterences_repo: "DBBrowne/blog"
  utterences_term: "pathname"
  enableGitInfo: true
  enableEmoji: true

markup:
  goldmark:
    renderer:
    # unsafe allows use of HTML and JavaScript in your Markdown
    # disable if your blog allows posts from untrusted authors
    unsafe: true
